// Category
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORY_DETAIL = "FETCH_CATEGORY_DETAIL";

// Product
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT_DETAIL = "FETCH_PRODUCT_DETAIL";

// Cart
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const DELETE_PRODUCT_IN_CART = "DELETE_PRODUCT_IN_CART";
export const UPDATE_PRODUCT_IN_CART = "UPDATE_PRODUCT_IN_CART";

// User
export const CHECKOUT = "CHECKOUT";
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const CONFIRM_OTP = "CONFIRM_OTP";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const MANAGE_ACCOUNT = "MANAGE_ACCOUNT";
